#!/bin/bash

## Some version by anv or whatever.
# trap "rm -rf /tmp/drae.$$" 1 2 3 9 15
 
# lynx -dump --nolist "http://buscon.rae.es/draeI/SrvltGUIBusUsual?TIPO_HTML=2&LEMA=$1" > /tmp/drae.$$
# cat /tmp/drae.$$ 2> /dev/null | tail -n $((`wc -l /tmp/drae.$$ 2> /dev/null | awk '{ print $1 ;}'`-1)) |
# grep -v "Todos los derechos reservados" #| cut -c 4-
 
# if [ -f /tmp/drae.$$ ]
# then rm /tmp/drae.$$
#fi

## 2007-05-13 - redondos

## Function
# function drae { result=$(lynx -dump --nolist "http://buscon.rae.es/draeI/SrvltGUIBusUsual?TIPOHTML=2&LEMA=$1"); tail -n +5 <<< "$result" | head -n -2; }

## Script
#lynx -dump --nolist "http://buscon.rae.es/draeI/SrvltGUIBusUsual?TIPOHTML=2&LEMA=$1" | 
#	tail -n +5 |
#	head -n -1 |
#	cut -b 4- |
#	iconv -f iso8859-1 -t utf8
## TODO: Fix this
##	#tee >( grep -q "La palabra .* en el Diccionario" && echo pipe2 && echo -e "No encontrado.\n" && exit 1 ); exit 0

## Better script
result=$(lynx -dump --nolist "http://buscon.rae.es/draeI/SrvltGUIBusUsual?TIPOHTML=2&LEMA=$1")
if grep -q "La palabra .* en el Diccionario" <<< "$result"; then
	echo -e "No encontrado.\n"
	exit 1
else
	if grep -q " Ver art.culo enmendado Ver conjugaci.n" <<< "$result"; then
		## grep -v's output value is not consistent between versions, therefore:
		result=$(grep -v " Ver art.culo enmendado Ver conjugaci.n" <<< "$result")
		tail=6
	else
		tail=5
	fi

	tail -n +$tail <<< "$result" |
	head -n -1 |
	cut -b 4- |
	iconv -f iso8859-1 -t utf8
fi
