#!/bin/zsh

base2()
{
	units=(B KB MB GB TB PB EB ZB YB)
	n=0
	while (((i = $1.0/2**(10*n)) >= 1024)); do
		((n++))
	done
	printf "%.2f %s\n" $i $units[n+2];
}

depth=1

while [[ -n $1 ]]; do
	case $1 in
	  (-[0-9]*) depth=${1#-} && shift;;
	esac
done

du --max-depth=$depth $@ | {
	while read size dir; do
		s+=("$size $dir")
	done
	for item in ${(On)s[@]}; do
		echo $(base2 ${item%% *}) ${item#* }
	done

}

# vim: ts=2:sw=2

