#!/bin/zsh

depth=1

while [[ -n $1 ]]; do
	case $1 in
	  (-[0-9]*) depth=${1#-} && shift;;
	esac
done

du --max-depth=$depth $@ | {
	while read size dir; do
		s+=("$size $dir")
	done
	print -l ${(On)s[@]}
}
