#!/bin/bash
# telefono - Lookup entries on paginasdoradas.com.ar based on telephone number
# Author: Angel Olivera <redondos@gmail.com>
# Date: 2007-05-11
# License: GPL-2

# Set the default area prefix to that of Mendoza
DEF_CODE=0261

# Replace dashes with spaces in $1

case $# in
	1)  # [<area_code><number>] or [<number>]
		set "${1//-/ }"
		numero_split=$(sed -re '
				/^0/!s#.*#0&#
				/^0/{
				/^011/{
				s#^(011)([0-9]{4})([0-9]{4})#\1\t\2\t\3#
				be} 
				s#^([0-9]{,4})([45][0-9]+)([0-9]{4})#\1\t\2\t\3#
				s#^([0-9]{,5})([45][0-9]+)([0-9]{4})#\1\t\2\t\3# }
				:e' <<< $1)
		read cod_area prefijo sufijo <<< "$numero_split"
		;;
	2) # [<area_code> <number>]
		cod_area=$1
		numero=$2
		;;
	*) # [<area_code> <prefix> <suffix>]
		cod_area=$1
		prefijo=$2
		sufijo=$3
		;;
esac

if [ $numero ]; then
	prefijo=${numero:0:$((${#numero}-4))}
	sufijo=${numero: -4}
fi

if ((cod_area==0)); then
	cod_area=$DEF_CODE
fi

echo -e "Búsqueda: $cod_area\t$prefijo\t$sufijo"

result=$(curl http://www.paginasdoradas.com/BuscarTelefonica.action -d "apellido=&provinciasId=0&localidad.descripcion=&telefono.area=${cod_area}&telefono.prefijo=${prefijo}&telefono.sufijo=${sufijo}" 2>/dev/null iconv -f iso-8859-1 -t utf-8 | vilistextum -nu - - \
 | sed -nr '/^[[:space:]]{3}[A-Z]{3,}.*'$sufijo'$/{p;n;n;n;p}')

if [ "$result" ]; then
	echo "Resultado:"
	echo "$result"
else
	echo "No hay resultados."
fi

